/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as DonRouteImport } from './routes/don'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AProposIndexRouteImport } from './routes/a-propos.index'
import { Route as AdminProgrammesRouteImport } from './routes/admin.programmes'
import { Route as AdminMeditationsRouteImport } from './routes/admin.meditations'
import { Route as AdminMediathequeRouteImport } from './routes/admin.mediatheque'
import { Route as AdminFinancesRouteImport } from './routes/admin.finances'
import { Route as AdminDepartementsRouteImport } from './routes/admin.departements'
import { Route as AProposProgrammesRouteImport } from './routes/a-propos.programmes'
import { Route as AProposDepartementsRouteImport } from './routes/a-propos.departements'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const DonRoute = DonRouteImport.update({
  id: '/don',
  path: '/don',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AProposIndexRoute = AProposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AProposRoute,
} as any)
const AdminProgrammesRoute = AdminProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeditationsRoute = AdminMeditationsRouteImport.update({
  id: '/meditations',
  path: '/meditations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediathequeRoute = AdminMediathequeRouteImport.update({
  id: '/mediatheque',
  path: '/mediatheque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancesRoute = AdminFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartementsRoute = AdminDepartementsRouteImport.update({
  id: '/departements',
  path: '/departements',
  getParentRoute: () => AdminRoute,
} as any)
const AProposProgrammesRoute = AProposProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AProposRoute,
} as any)
const AProposDepartementsRoute = AProposDepartementsRouteImport.update({
  id: '/departements',
  path: '/departements',
  getParentRoute: () => AProposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/don': typeof DonRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/a-propos/departements': typeof AProposDepartementsRoute
  '/a-propos/programmes': typeof AProposProgrammesRoute
  '/admin/departements': typeof AdminDepartementsRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/mediatheque': typeof AdminMediathequeRoute
  '/admin/meditations': typeof AdminMeditationsRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/a-propos/': typeof AProposIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/don': typeof DonRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/a-propos/departements': typeof AProposDepartementsRoute
  '/a-propos/programmes': typeof AProposProgrammesRoute
  '/admin/departements': typeof AdminDepartementsRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/mediatheque': typeof AdminMediathequeRoute
  '/admin/meditations': typeof AdminMeditationsRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/a-propos': typeof AProposIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/don': typeof DonRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/a-propos/departements': typeof AProposDepartementsRoute
  '/a-propos/programmes': typeof AProposProgrammesRoute
  '/admin/departements': typeof AdminDepartementsRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/mediatheque': typeof AdminMediathequeRoute
  '/admin/meditations': typeof AdminMeditationsRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/a-propos/': typeof AProposIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/connexion'
    | '/contact'
    | '/don'
    | '/inscription'
    | '/profil'
    | '/a-propos/departements'
    | '/a-propos/programmes'
    | '/admin/departements'
    | '/admin/finances'
    | '/admin/mediatheque'
    | '/admin/meditations'
    | '/admin/programmes'
    | '/a-propos/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/contact'
    | '/don'
    | '/inscription'
    | '/profil'
    | '/a-propos/departements'
    | '/a-propos/programmes'
    | '/admin/departements'
    | '/admin/finances'
    | '/admin/mediatheque'
    | '/admin/meditations'
    | '/admin/programmes'
    | '/a-propos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/connexion'
    | '/contact'
    | '/don'
    | '/inscription'
    | '/profil'
    | '/a-propos/departements'
    | '/a-propos/programmes'
    | '/admin/departements'
    | '/admin/finances'
    | '/admin/mediatheque'
    | '/admin/meditations'
    | '/admin/programmes'
    | '/a-propos/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DonRoute: typeof DonRoute
  InscriptionRoute: typeof InscriptionRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don': {
      id: '/don'
      path: '/don'
      fullPath: '/don'
      preLoaderRoute: typeof DonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/a-propos/': {
      id: '/a-propos/'
      path: '/'
      fullPath: '/a-propos/'
      preLoaderRoute: typeof AProposIndexRouteImport
      parentRoute: typeof AProposRoute
    }
    '/admin/programmes': {
      id: '/admin/programmes'
      path: '/programmes'
      fullPath: '/admin/programmes'
      preLoaderRoute: typeof AdminProgrammesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meditations': {
      id: '/admin/meditations'
      path: '/meditations'
      fullPath: '/admin/meditations'
      preLoaderRoute: typeof AdminMeditationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mediatheque': {
      id: '/admin/mediatheque'
      path: '/mediatheque'
      fullPath: '/admin/mediatheque'
      preLoaderRoute: typeof AdminMediathequeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finances': {
      id: '/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AdminFinancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departements': {
      id: '/admin/departements'
      path: '/departements'
      fullPath: '/admin/departements'
      preLoaderRoute: typeof AdminDepartementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/a-propos/programmes': {
      id: '/a-propos/programmes'
      path: '/programmes'
      fullPath: '/a-propos/programmes'
      preLoaderRoute: typeof AProposProgrammesRouteImport
      parentRoute: typeof AProposRoute
    }
    '/a-propos/departements': {
      id: '/a-propos/departements'
      path: '/departements'
      fullPath: '/a-propos/departements'
      preLoaderRoute: typeof AProposDepartementsRouteImport
      parentRoute: typeof AProposRoute
    }
  }
}

interface AProposRouteChildren {
  AProposDepartementsRoute: typeof AProposDepartementsRoute
  AProposProgrammesRoute: typeof AProposProgrammesRoute
  AProposIndexRoute: typeof AProposIndexRoute
}

const AProposRouteChildren: AProposRouteChildren = {
  AProposDepartementsRoute: AProposDepartementsRoute,
  AProposProgrammesRoute: AProposProgrammesRoute,
  AProposIndexRoute: AProposIndexRoute,
}

const AProposRouteWithChildren =
  AProposRoute._addFileChildren(AProposRouteChildren)

interface AdminRouteChildren {
  AdminDepartementsRoute: typeof AdminDepartementsRoute
  AdminFinancesRoute: typeof AdminFinancesRoute
  AdminMediathequeRoute: typeof AdminMediathequeRoute
  AdminMeditationsRoute: typeof AdminMeditationsRoute
  AdminProgrammesRoute: typeof AdminProgrammesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepartementsRoute: AdminDepartementsRoute,
  AdminFinancesRoute: AdminFinancesRoute,
  AdminMediathequeRoute: AdminMediathequeRoute,
  AdminMeditationsRoute: AdminMeditationsRoute,
  AdminProgrammesRoute: AdminProgrammesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DonRoute: DonRoute,
  InscriptionRoute: InscriptionRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
